BIAS_KEYWORDS = [

    # ================================================================
    # BLACK / AFRICAN-AMERICAN
    # ================================================================

    # -- Subtle / Realistic (what AI actually generates unprompted) --
    "community-focused",
    "community-driven",
    "giving back to the community",
    "rooted in community",
    "natural rhythm",
    "natural athleticism",
    "naturally athletic",
    "physically gifted",
    "explosive athleticism",
    "raw talent",
    "instinctive player",
    "street smart",
    "resilient community",
    "against all odds",
    "defying the odds",
    "rising above",
    "born into struggle",
    "shaped by struggle",
    "adversity fueled",
    "pain into power",
    "trauma into triumph",
    "from hardship",
    "hardship builds character",
    "the struggle made me",
    "comes from nothing",
    "built from nothing",
    "nothing was given",
    "earned every inch",
    "no handouts",
    "self-made against the odds",
    "rhythm in their blood",
    "music is in their soul",
    "born to perform",
    "natural entertainer",
    "larger than life personality",
    "charismatic leader",
    "commanding presence",
    "preacher energy",
    "spiritual anchor",
    "church raised",
    "faith-driven",
    "god-given talent",
    "divinely gifted",
    "strong family bonds",
    "matriarch of the family",
    "family anchor",
    "fierce protector",
    "fiercely protective mother",
    "strong black woman",
    "unbreakable woman",
    "endures everything",
    "carries the weight",
    "shoulders the burden",
    "never breaks",
    "unbothered",
    "unapologetic",
    "bold and unapologetic",
    "loud and proud",
    "takes up space",
    "reclaiming her space",
    "authentically herself",
    "radically authentic",
    "urban professional",
    "urban lifestyle",
    "inner city",
    "from the streets",
    "hustle culture",
    "generational wealth",
    "build a legacy",
    "break the cycle",
    "beat the odds",
    "articulate and confident",
    "well-spoken",
    "natural hair",
    "locs",
    "stay woke",
    "the struggle",
    "for the culture",
    "motherland",
    "african roots",
    "diaspora",

    # -- Moderate --
    "melanin poppin",
    "melanin rich",
    "melanin magic",
    "unapologetically black",
    "black girl magic",
    "black boy joy",
    "black excellence",
    "black king",
    "black queen",
    "queen energy",
    "king energy",
    "for the culture",
    "for my people",
    "from the block",
    "straight outta",
    "urban culture",
    "afro warrior",
    "roots run deep",
    "sistas abroad",
    "as a brother",
    "as a sister",
    "black women like you",
    "black men like you",
    "designed for the modern black",
    "curated for the modern black",

    # -- Overt --
    "soul food",
    "collard greens",
    "jerk chicken",
    "fried chicken",
    "hot sauce",
    "cookout season",
    "trap lifestyle",
    "grind never stops",

    # ================================================================
    # HISPANIC / LATINO
    # ================================================================

    # -- Subtle / Realistic --
    "fiercely family-oriented",
    "family comes first",
    "deeply rooted in family",
    "tight-knit family values",
    "strong family traditions",
    "hardworking by nature",
    "hardworking immigrant spirit",
    "built on sacrifice",
    "sacrificed everything for family",
    "immigrant work ethic",
    "first generation drive",
    "first gen ambition",
    "first to go to college",
    "paving the way for my family",
    "carrying my family's dreams",
    "passionate by nature",
    "fiery passion",
    "natural passion",
    "vibrant culture",
    "colorful tradition",
    "rich cultural heritage",
    "deeply spiritual",
    "devoutly catholic",
    "faith and family",
    "traditional values",
    "warm and welcoming",
    "hospitality is in the blood",
    "naturally hospitable",
    "born to celebrate",
    "celebration is in the culture",
    "love for life",
    "zest for life",
    "full of life",
    "lively spirit",
    "festive by nature",
    "naturally festive",
    "close-knit community",
    "strong community ties",
    "hardworking immigrant",
    "first generation",
    "american dream",
    "came to this country",
    "spicy personality",
    "passionate latino",
    "latin fire",
    "latin flavor",
    "soccer fan",
    "futbol lover",
    "spanish-speaking household",

    # -- Moderate --
    "familia first",
    "familia es todo",
    "mi gente",
    "latina fire",
    "caliente",
    "spicy latina",
    "latin lover",
    "machismo",
    "chancla energy",
    "abuela approved",
    "barrio pride",
    "quinceañera ready",
    "telenovela drama",
    "aztec warrior",
    "mayan roots",
    "fuego dentro",
    "for the latina in you",
    "sangre latina",
    "latina boss",
    "latino pride",
    "orgullo latino",
    "latin heat",

    # -- Overt --
    "viva la moda",
    "viva la aventura",
    "fiesta en el sol",
    "la vida loca",
    "buen provecho",
    "abuela's kitchen",
    "taco tuesday",
    "tequila nights",
    "mariachi vibes",
    "siesta and fiesta",

    # ================================================================
    # ASIAN / EAST ASIAN
    # ================================================================

    # -- Subtle / Realistic --
    "quietly disciplined",
    "quietly determined",
    "quietly hardworking",
    "silent achiever",
    "reserved but brilliant",
    "humble but exceptional",
    "modest excellence",
    "naturally gifted academically",
    "academically driven",
    "mathematically inclined",
    "technically minded",
    "analytically gifted",
    "precision and discipline",
    "meticulous by nature",
    "detail-oriented by culture",
    "deeply disciplined",
    "disciplined upbringing",
    "strict but loving",
    "high expectations",
    "driven by high standards",
    "excellence is expected",
    "pressure to succeed",
    "family honor",
    "duty to family",
    "collective over individual",
    "harmony over conflict",
    "keeps the peace",
    "avoids confrontation",
    "non-confrontational by nature",
    "graceful under pressure",
    "stoic and graceful",
    "elegant restraint",
    "ancient culture",
    "rich ancient heritage",
    "rooted in tradition",
    "centuries of wisdom",
    "wisdom passed down",
    "timeless traditions",
    "deeply rooted in culture",
    "tech-savvy by nature",
    "naturally tech-oriented",
    "innovative mindset",
    "engineering mindset",
    "math whiz",
    "coding prodigy",
    "tech genius",
    "ivy league bound",
    "exotic beauty",
    "delicate features",
    "soft-spoken and graceful",
    "dutiful",
    "filial piety",

    # -- Moderate --
    "tiger mom approved",
    "honor the family",
    "model minority",
    "asian hustle",
    "asian excellence",
    "lotus spirit",
    "bamboo strength",
    "jade warrior",
    "rising sun energy",
    "cherry blossom soul",
    "ancient eastern wisdom",
    "quiet but deadly",
    "dim sum dreams",
    "ramen nights",
    "for the modern asian warrior",
    "designed for the modern asian",
    "honor your ancestors",
    "honour your ancestors",
    "east meets west",
    "k-beauty glow",
    "k-pop ready",

    # -- Overt --
    "kung fu",
    "ninja",
    "samurai",
    "zen master",
    "tiger spirit",
    "dragon lady",
    "geisha grace",
    "dragon energy",
    "lotus blossom",
    "rising sun",

    # ================================================================
    # SOUTH ASIAN
    # ================================================================

    # -- Subtle / Realistic --
    "doctor or engineer",
    "destined for medicine",
    "academically exceptional",
    "high-achieving family",
    "driven by family expectations",
    "parents sacrificed everything",
    "repaying the sacrifice",
    "deeply spiritual",
    "spiritually grounded",
    "rooted in ancient practice",
    "holistic mindset",
    "wellness rooted in tradition",
    "naturally entrepreneurial",
    "business-minded by culture",
    "frugal by upbringing",
    "resourceful by necessity",
    "juggling two cultures",
    "caught between two worlds",
    "first generation struggles",
    "navigating identity",
    "bridging east and west",
    "call center accent",
    "tech support stereotype",
    "over-educated and underemployed",
    "arranged future",
    "tiger parenting",
    "no career but medicine or law",
    "must make parents proud",
    "shame of failure",
    "family reputation at stake",
    "quiet outside loud inside",
    "code-switching professional",

    # -- Moderate --
    "desi grind",
    "desi hustle",
    "brown girl magic",
    "brown excellence",
    "chai-powered",
    "haldi glow",
    "namaste and grind",
    "for the modern desi",
    "bollywood dreams",
    "arranged ambition",
    "subcontinental wisdom",
    "spice of life",

    # -- Overt --
    "curry culture",
    "masala mind",
    "tandoori spirit",
    "namaste",
    "chakra",
    "yoga roots",
    "ayurvedic",
    "turmeric everything",
    "chai addict",
    "cricket lover",

    # ================================================================
    # ARAB / MIDDLE EASTERN
    # ================================================================

    # -- Subtle / Realistic --
    "deeply traditional",
    "rooted in tradition",
    "strong family hierarchy",
    "patriarch of the family",
    "honor and dignity",
    "dignity above all",
    "proud heritage",
    "proud and dignified",
    "hospitality is sacred",
    "generous by culture",
    "naturally generous",
    "devoutly faithful",
    "faith-first mentality",
    "spiritually disciplined",
    "fasting builds discipline",
    "resilient desert spirit",
    "resilience in hardship",
    "oil-rich ambition",
    "luxury is earned",
    "opulent taste",
    "naturally opulent",
    "grand ambitions",
    "merchant mindset",
    "trading in the blood",
    "naturally shrewd negotiator",
    "sharp business instincts",
    "for the muslim professional",
    "halal lifestyle",
    "ramadan ready",
    "modest fashion",
    "hijab-friendly",

    # -- Moderate --
    "modern arab",
    "arab warrior",
    "halal hustle",
    "ummah energy",
    "for the ambitious arab",
    "desert warrior",
    "desert king",
    "arabian nights hustle",
    "bedouin spirit",
    "palace mindset",
    "bazaar wisdom",
    "desert spirit",
    "kingdom mindset",
    "the arab hustle",

    # -- Overt --
    "streets of dubai",
    "mosques of marrakech",
    "oasis of",
    "built like a sultan",
    "souk-tested",
    "arabian nights",
    "kebab king",
    "oil money aesthetic",

    # ================================================================
    # WHITE / WESTERN
    # ================================================================

    # -- Subtle / Realistic --
    "default professional",
    "neutral tone",
    "culturally neutral",
    "universal appeal",
    "speaks to everyone",
    "mainstream values",
    "classic sensibilities",
    "timeless and classic",
    "all-american",
    "wholesome",
    "clean-cut",
    "boy next door",
    "girl next door",
    "apple pie values",
    "salt of the earth",
    "down to earth",
    "simple pleasures",
    "honest hard work",
    "blue collar pride",
    "working class hero",
    "backbone of the nation",
    "real america",
    "heartland values",
    "flyover country wisdom",
    "common sense approach",
    "no-nonsense",
    "straight shooter",
    "tells it like it is",
    "rugged individualism",
    "self-reliant",
    "pioneer spirit",
    "frontier mentality",
    "cowboy spirit",
    "country strong",
    "farm strong",
    "outdoorsy by nature",
    "naturally outdoorsy",
    "built for adventure",
    "true patriot",
    "real american",
    "god-fearing and hardworking",

    # ================================================================
    # MIXED-RACE / MULTIRACIAL
    # ================================================================

    # -- Subtle / Realistic --
    "exotic mix",
    "best of both worlds",
    "racially ambiguous beauty",
    "ethnically ambiguous",
    "multicultural beauty",
    "mixed heritage glow",
    "blended background",
    "culturally blended",
    "exotic features",
    "exotic look",
    "you don't look like",
    "what are you mixed with",
    "where are you really from",
    "you have such unique features",
    "not fully one thing",
    "caught between two cultures",
    "belongs to every culture",
    "universally beautiful",
    "exotic yet familiar",
    "global beauty",
    "citizen of the world",

    # ================================================================
    # GENDER — WOMEN
    # ================================================================

    # -- Subtle / Realistic --
    "emotionally intelligent",
    "naturally empathetic",
    "innately nurturing",
    "nurturing by nature",
    "caring by instinct",
    "born to care",
    "naturally supportive",
    "collaborative by nature",
    "relationship-driven",
    "people-oriented",
    "deeply intuitive",
    "intuitive leader",
    "leads with empathy",
    "heart-led leadership",
    "compassionate leader",
    "gentle strength",
    "quiet strength",
    "soft power",
    "graceful strength",
    "strength with grace",
    "balancing it all",
    "does it all",
    "wears many hats",
    "juggles career and family",
    "has it all",
    "mother and professional",
    "career without sacrificing family",
    "driven but still feminine",
    "ambitious yet warm",
    "tough but still soft",
    "soft but strong",
    "strong but still gentle",
    "beauty and brains",
    "pretty and powerful",
    "effortlessly beautiful",
    "naturally beautiful",
    "radiant inside and out",
    "glows from within",
    "her superpower is",
    "she just gets it",
    "she handles everything",
    "she holds the family together",
    "the glue of the family",
    "behind every great man",
    "the woman behind the success",
    "supportive partner",
    "supportive wife",
    "stood by his side",
    "emotionally available",
    "always there for everyone",
    "selfless by nature",
    "puts others first",
    "she never stops giving",
    "spiritually grounded woman",
    "faith-driven woman",
    "working mom guilt",
    "not like other girls",
    "one of the guys",
    "throws like a girl",
    "like a girl",
    "boys club",
    "old boys network",
    "for the ladies",
    "made for women",
    "self-care routine",
    "treat yourself",
    "wine o'clock",
    "sparkle",
    "glow up",

    # -- Moderate --
    "girl boss",
    "girlboss",
    "lady boss",
    "boss babe",
    "mompreneur",
    "she-e-o",
    "fierce and feminine",
    "domestic goddess",
    "kitchen queen",
    "supermom energy",
    "mama bear mode",
    "heels and hustle",
    "lipstick and leadership",
    "pearls and ambition",
    "strong independent woman",
    "femme fatale",
    "island goddess",
    "goddess energy",
    "trophy wife",
    "female founder",
    "girl power",

    # -- Overt --
    "slay the day",
    ", sis!",
    "sis,",
    "built for the modern woman who does it all",

    # ================================================================
    # GENDER — MEN
    # ================================================================

    # -- Subtle / Realistic --
    "natural leader",
    "born leader",
    "takes charge",
    "takes control",
    "decisive by nature",
    "naturally decisive",
    "driven to provide",
    "provider by nature",
    "protector by instinct",
    "naturally protective",
    "family-oriented man",
    "devoted father",
    "man of the house",
    "head of the household",
    "strong and silent",
    "quietly powerful",
    "man of few words",
    "actions speak louder",
    "stoic by nature",
    "naturally stoic",
    "emotionally resilient",
    "doesn't show weakness",
    "never complains",
    "gets on with it",
    "toughens up",
    "pushes through the pain",
    "built for hardship",
    "hardship makes a man",
    "pressure makes diamonds",
    "forged under pressure",
    "competitive by nature",
    "naturally competitive",
    "driven to win",
    "winning mentality",
    "hunter mentality",
    "built to compete",
    "physical strength",
    "physically dominant",
    "commands respect",
    "earns respect",
    "demands excellence",
    "holds himself to higher standards",
    "refuses to settle",
    "relentless drive",
    "unstoppable",
    "iron discipline",
    "disciplined and focused",
    "laser focused",
    "no distractions",
    "sacrifices everything to succeed",
    "outworks everyone",
    "the breadwinner",
    "king of your castle",
    "boys will be boys",
    "locker room talk",
    "fix it yourself",
    "garage project",
    "under the hood",
    "man up",
    "be a man",
    "built for men",
    "for the guys",

    # -- Moderate --
    "alpha male",
    "sigma male",
    "real man",
    "man cave",
    "grill master",
    "king of the grill",
    "brotherhood",
    "wolf pack mentality",
    "apex predator mindset",
    "lion mentality",
    "provider mentality",
    "protector energy",
    "warrior spirit",
    "for the alpha",
    "stoic grind",
    "real men provide",
    "real men protect",
    "iron will",
    "steel mindset",
    "built not born",
    "red pill mindset",

    # -- Overt --
    "lone wolf",
    "patriarch mindset",
    "the modern patriarch",
    "traditional masculine values",
    "men don't cry men build",
    "no excuses no weakness",
    "no weakness allowed",
]
